generate extended enums and fix dedup
extended enums are useful for larger enums since they allow more
efficients access, i.e. direct index lookup or binary search.
Normal enum (cf. VALS()) require linear search.

This also fixes the following wireshark commit check:

    Error: hf_eti[foobar] is passing the address of a pointer to VALS in xyz.c

The dedup logic now also considers key values, since key names alone
aren't unique.